### ISSUE TITLE
shell下看不到选择条，不知道选择到哪个了

### ISSUE THREAD

**Issue by 692568516** [kaolengmian7/v2ex-tui#3]
![image](https://github.com/user-attachments/assets/2176acac-eb66-4329-a39c-e04f8d6fa588)

**Comment by 692568516** [comment]
另外鼠标操作好像有问题，当吧背景调整为白色，则可以看到选择条，上下键选择某条话题后，使用鼠标点击另外一个话题，则鼠标点击的不生效，会跳转到上下键选择的这条话题

**Comment by kaolengmian7** [comment]
没有选择条的话，应该是本工具的 UI 主题和你本身的终端主题冲突了，可以换个主题试试。

另：无论是键盘还是鼠标，点击时都是按照光标的位置来选择话题的。

**Comment by shenweiyan** [comment]
同样的问题，换了 MobaXtern sessions 的主题好像也不行
